// <auto-generated />
using System;
using HamzaTex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamzaTex.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112134038_InitialMySqlMigration")]
    partial class InitialMySqlMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HamzaTex.Api.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<Guid?>("ClientTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_type_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("credit_limit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("opening_balance")
                        .HasDefaultValueSql("0");

                    b.Property<int>("Phone")
                        .HasColumnType("int")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("clients_pkey");

                    b.HasIndex("ClientTypeId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ClientType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("client_types_pkey");

                    b.ToTable("client_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<Guid?>("ExpenseTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("expense_type_id");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid?>("TransModeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trans_mode_id");

                    b.HasKey("Id")
                        .HasName("expenses_pkey");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("TransModeId");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ExpenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("expense_types_pkey");

                    b.ToTable("expense_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("logins_pkey");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("logins", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("movement_sources_pkey");

                    b.ToTable("movement_sources", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("movement_types_pkey");

                    b.ToTable("movement_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<Guid?>("PaymentTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payment_type_id");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("order_lines_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("order_statuses_pkey");

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PartyClientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("party_client_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<Guid?>("PaymentDirectionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payment_direction_id");

                    b.Property<Guid?>("PaymentTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TransModeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trans_mode_id");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex("PartyClientId");

                    b.HasIndex("PaymentDirectionId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("TransModeId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentDirection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_directions_pkey");

                    b.ToTable("payment_directions", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_types_pkey");

                    b.ToTable("payment_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("DefaultCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("default_cost")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("DefaultPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("default_price")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("reorder_level");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sku");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex(new[] { "Sku" }, "products_sku_key")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PaymentTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payment_type_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("purchases_pkey");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("purchase_lines_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("purchase_lines", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("MovementDate")
                        .HasColumnType("date")
                        .HasColumnName("movement_date");

                    b.Property<Guid?>("MovementSourceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movement_source_id");

                    b.Property<Guid?>("MovementTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movement_type_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("stock_movements_pkey");

                    b.HasIndex("MovementSourceId");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("trans_categories_pkey");

                    b.ToTable("trans_categories", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("trans_modes_pkey");

                    b.ToTable("trans_modes", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("trans_types_pkey");

                    b.ToTable("trans_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("TransCategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trans_category_id");

                    b.Property<DateOnly>("TransDate")
                        .HasColumnType("date")
                        .HasColumnName("trans_date");

                    b.Property<Guid?>("TransModeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trans_mode_id");

                    b.Property<Guid?>("TransTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trans_type_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransCategoryId");

                    b.HasIndex("TransModeId");

                    b.HasIndex("TransTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Name" }, "users_name_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_roles_pkey");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.VClientBalance", b =>
                {
                    b.Property<decimal?>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_id");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.ToTable((string)null);

                    b.ToView("v_client_balance", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.VMonthlyProfitLoss", b =>
                {
                    b.Property<decimal?>("GrossProfit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("gross_profit");

                    b.Property<DateTime?>("Month")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("month");

                    b.Property<decimal?>("NetProfit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("net_profit");

                    b.Property<decimal?>("TotalExpenses")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_expenses");

                    b.Property<decimal?>("TotalPurchases")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_purchases");

                    b.Property<decimal?>("TotalSales")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_sales");

                    b.ToTable((string)null);

                    b.ToView("v_monthly_profit_loss", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Client", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ClientType", "ClientType")
                        .WithMany("Clients")
                        .HasForeignKey("ClientTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("clients_client_type_id_fkey");

                    b.Navigation("ClientType");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Expense", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ExpenseType", "ExpenseType")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("expenses_expense_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransMode", "TransMode")
                        .WithMany("Expenses")
                        .HasForeignKey("TransModeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("expenses_trans_mode_id_fkey");

                    b.Navigation("ExpenseType");

                    b.Navigation("TransMode");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Login", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("HamzaTex.Api.Entities.Login", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("logins_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Order", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_client_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PaymentType", "PaymentType")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_payment_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_status_id_fkey");

                    b.Navigation("Client");

                    b.Navigation("PaymentType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderLine", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_lines_order_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("order_lines_product_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Payment", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Client", "PartyClient")
                        .WithMany("Payments")
                        .HasForeignKey("PartyClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_party_client_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PaymentDirection", "PaymentDirection")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentDirectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_payment_direction_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PaymentType", null)
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId");

                    b.HasOne("HamzaTex.Api.Entities.TransMode", "TransMode")
                        .WithMany("Payments")
                        .HasForeignKey("TransModeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_trans_mode_id_fkey");

                    b.Navigation("PartyClient");

                    b.Navigation("PaymentDirection");

                    b.Navigation("TransMode");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Purchase", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.PaymentType", "PaymentType")
                        .WithMany("Purchases")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchases_payment_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Client", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchases_supplier_id_fkey");

                    b.Navigation("PaymentType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PurchaseLine", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchase_lines_product_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_lines_purchase_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.StockMovement", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.MovementSource", "MovementSource")
                        .WithMany("StockMovements")
                        .HasForeignKey("MovementSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("stock_movements_movement_source_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.MovementType", "MovementType")
                        .WithMany("StockMovements")
                        .HasForeignKey("MovementTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("stock_movements_movement_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("stock_movements_product_id_fkey");

                    b.Navigation("MovementSource");

                    b.Navigation("MovementType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Transaction", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_client_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_product_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransCategory", "TransCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("TransCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_trans_category_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransMode", "TransMode")
                        .WithMany("Transactions")
                        .HasForeignKey("TransModeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_trans_mode_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransType", "TransType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_trans_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_user_id_fkey");

                    b.Navigation("Client");

                    b.Navigation("Product");

                    b.Navigation("TransCategory");

                    b.Navigation("TransMode");

                    b.Navigation("TransType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.User", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Client", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Purchases");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ClientType", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ExpenseType", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementSource", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementType", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentDirection", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentType", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("PurchaseLines");

                    b.Navigation("StockMovements");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseLines");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransCategory", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransMode", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
