// <auto-generated />
using System;
using HamzaTex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamzaTex.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415224000_FixMonthlyCreditDebitView")]
    partial class FixMonthlyCreditDebitView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HamzaTex.Api.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "IX_users_email");

                    b.HasIndex(new[] { "IsActive" }, "IX_users_is_active");

                    b.HasIndex(new[] { "IsActive", "CreatedAt" }, "IX_users_is_active_created_at");

                    b.HasIndex(new[] { "Name" }, "users_name_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int?>("ClientTypeId")
                        .HasColumnType("int")
                        .HasColumnName("client_type_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("credit_limit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("opening_balance")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("clients_pkey");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "IsActive" }, "IX_clients_is_active");

                    b.HasIndex(new[] { "Name" }, "IX_clients_name");

                    b.HasIndex(new[] { "Phone" }, "IX_clients_phone");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ClientType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("client_types_pkey");

                    b.ToTable("client_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<int?>("ExpenseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("expense_type_id");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("TransCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("trans_category_id");

                    b.Property<int?>("TransModeId")
                        .HasColumnType("int")
                        .HasColumnName("trans_mode_id");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("expenses_pkey");

                    b.HasIndex("TransCategoryId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ExpenseDate" }, "IX_expenses_expense_date");

                    b.HasIndex(new[] { "ExpenseTypeId" }, "IX_expenses_expense_type_id");

                    b.HasIndex(new[] { "TransModeId" }, "IX_expenses_trans_mode_id");

                    b.HasIndex(new[] { "ExpenseTypeId", "ExpenseDate" }, "IX_expenses_type_date");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("expense_types_pkey");

                    b.ToTable("expense_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("movement_sources_pkey");

                    b.ToTable("movement_sources", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("movement_types_pkey");

                    b.ToTable("movement_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("payment_type_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex(new[] { "ClientId", "OrderDate" }, "IX_orders_client_date");

                    b.HasIndex(new[] { "ClientId" }, "IX_orders_client_id");

                    b.HasIndex(new[] { "OrderDate" }, "IX_orders_order_date");

                    b.HasIndex(new[] { "PaymentTypeId" }, "IX_orders_payment_type_id");

                    b.HasIndex(new[] { "StatusId", "OrderDate" }, "IX_orders_status_date");

                    b.HasIndex(new[] { "StatusId" }, "IX_orders_status_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("order_lines_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("order_statuses_pkey");

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsReversed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reversed");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("OriginalPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("original_payment_id");

                    b.Property<int?>("PartyClientId")
                        .HasColumnType("int")
                        .HasColumnName("party_client_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentDirectionId")
                        .HasColumnType("int")
                        .HasColumnName("payment_direction_id");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ReversedByPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("reversed_by_payment_id");

                    b.Property<int?>("TransModeId")
                        .HasColumnType("int")
                        .HasColumnName("trans_mode_id");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex("OriginalPaymentId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ReversedByPaymentId");

                    b.HasIndex("TransactionId");

                    b.HasIndex(new[] { "PartyClientId", "PaymentDate" }, "IX_payments_client_date");

                    b.HasIndex(new[] { "IsReversed" }, "IX_payments_is_reversed");

                    b.HasIndex(new[] { "PartyClientId" }, "IX_payments_party_client_id");

                    b.HasIndex(new[] { "PaymentDate" }, "IX_payments_payment_date");

                    b.HasIndex(new[] { "PaymentDirectionId" }, "IX_payments_payment_direction_id");

                    b.HasIndex(new[] { "TransModeId" }, "IX_payments_trans_mode_id");

                    b.HasIndex(new[] { "UserId" }, "IX_payments_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    b.HasKey("Id")
                        .HasName("payment_allocations_pkey");

                    b.HasIndex(new[] { "OrderId" }, "IX_payment_allocations_order_id");

                    b.HasIndex(new[] { "PaymentId" }, "IX_payment_allocations_payment_id");

                    b.HasIndex(new[] { "PurchaseId" }, "IX_payment_allocations_purchase_id");

                    b.ToTable("payment_allocations", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_directions_pkey");

                    b.ToTable("payment_directions", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_types_pkey");

                    b.ToTable("payment_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageCost")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("average_cost");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("average_price");

                    b.Property<int>("CostChangeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("cost_change_count");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("DefaultCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("default_cost")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("DefaultPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("default_price")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("PriceChangeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("price_change_count");

                    b.Property<decimal?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("quantity")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("reorder_level");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sku");

                    b.Property<decimal?>("TotalQuantityPurchased")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_quantity_purchased")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("TotalQuantitySold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_quantity_sold")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex(new[] { "IsActive" }, "IX_products_is_active");

                    b.HasIndex(new[] { "IsActive", "Name" }, "IX_products_is_active_name");

                    b.HasIndex(new[] { "Name" }, "IX_products_name");

                    b.HasIndex(new[] { "Sku" }, "products_sku_key")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ProductUser", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("ProductId", "UserId")
                        .HasName("product_users_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("product_users", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("payment_type_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("purchases_pkey");

                    b.HasIndex(new[] { "PaymentTypeId" }, "IX_purchases_payment_type_id");

                    b.HasIndex(new[] { "PurchaseDate" }, "IX_purchases_purchase_date");

                    b.HasIndex(new[] { "StatusId" }, "IX_purchases_status_id");

                    b.HasIndex(new[] { "SupplierId", "PurchaseDate" }, "IX_purchases_supplier_date");

                    b.HasIndex(new[] { "SupplierId" }, "IX_purchases_supplier_id");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PurchaseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("purchase_lines_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("purchase_lines", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PurchaseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("purchase_statuses_pkey");

                    b.ToTable("purchase_statuses", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("longtext")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("Token")
                        .HasDatabaseName("idx_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageCostAtMovement")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("average_cost_at_movement");

                    b.Property<decimal?>("AveragePriceAtMovement")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("average_price_at_movement");

                    b.Property<DateOnly>("MovementDate")
                        .HasColumnType("date")
                        .HasColumnName("movement_date");

                    b.Property<int?>("MovementSourceId")
                        .HasColumnType("int")
                        .HasColumnName("movement_source_id");

                    b.Property<int?>("MovementTypeId")
                        .HasColumnType("int")
                        .HasColumnName("movement_type_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("qty")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("stock_movements_pkey");

                    b.HasIndex(new[] { "MovementDate" }, "IX_stock_movements_movement_date");

                    b.HasIndex(new[] { "MovementSourceId" }, "IX_stock_movements_movement_source_id");

                    b.HasIndex(new[] { "MovementTypeId" }, "IX_stock_movements_movement_type_id");

                    b.HasIndex(new[] { "ProductId", "MovementDate" }, "IX_stock_movements_product_date");

                    b.HasIndex(new[] { "ProductId" }, "IX_stock_movements_product_id");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("trans_categories_pkey");

                    b.ToTable("trans_categories", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("trans_modes_pkey");

                    b.ToTable("trans_modes", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("trans_types_pkey");

                    b.ToTable("trans_types", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseId");

                    b.Property<int?>("TransCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("trans_category_id");

                    b.Property<DateOnly>("TransDate")
                        .HasColumnType("date")
                        .HasColumnName("trans_date");

                    b.Property<int?>("TransModeId")
                        .HasColumnType("int")
                        .HasColumnName("trans_mode_id");

                    b.Property<int?>("TransTypeId")
                        .HasColumnType("int")
                        .HasColumnName("trans_type_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex(new[] { "ClientId", "TransDate" }, "IX_transactions_client_date");

                    b.HasIndex(new[] { "ClientId" }, "IX_transactions_client_id");

                    b.HasIndex(new[] { "OrderId" }, "IX_transactions_order_id");

                    b.HasIndex(new[] { "ProductId" }, "IX_transactions_product_id");

                    b.HasIndex(new[] { "PurchaseId" }, "IX_transactions_purchase_id");

                    b.HasIndex(new[] { "TransCategoryId" }, "IX_transactions_trans_category_id");

                    b.HasIndex(new[] { "TransDate" }, "IX_transactions_trans_date");

                    b.HasIndex(new[] { "TransModeId" }, "IX_transactions_trans_mode_id");

                    b.HasIndex(new[] { "TransTypeId" }, "IX_transactions_trans_type_id");

                    b.HasIndex(new[] { "TransTypeId", "TransDate" }, "IX_transactions_type_date");

                    b.HasIndex(new[] { "UserId", "TransDate" }, "IX_transactions_user_date");

                    b.HasIndex(new[] { "UserId" }, "IX_transactions_user_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_roles_pkey");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.VClientBalance", b =>
                {
                    b.Property<decimal?>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance");

                    b.Property<int?>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.ToTable((string)null);

                    b.ToView("v_client_balance", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.VMonthlyCreditDebit", b =>
                {
                    b.Property<decimal?>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Month")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("month");

                    b.Property<decimal?>("TotalCredit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_credit");

                    b.Property<decimal?>("TotalDebit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_debit");

                    b.ToTable((string)null);

                    b.ToView("v_monthly_credit_debit", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.VMonthlyProfitLoss", b =>
                {
                    b.Property<decimal?>("GrossProfit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("gross_profit");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Month")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("month");

                    b.Property<decimal?>("NetProfit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("net_profit");

                    b.Property<decimal?>("TotalExpenses")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_expenses");

                    b.Property<decimal?>("TotalPurchases")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_purchases");

                    b.Property<decimal?>("TotalSales")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_sales");

                    b.ToTable((string)null);

                    b.ToView("v_monthly_profit_loss", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnet_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnet_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnet_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnet_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnet_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnet_user_tokens", (string)null);
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ApplicationUser", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Client", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ClientType", "ClientType")
                        .WithMany("Clients")
                        .HasForeignKey("ClientTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("clients_client_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("clients_user_id_fkey");

                    b.Navigation("ClientType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Expense", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ExpenseType", "ExpenseType")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("expenses_expense_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransCategory", "TransCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("TransCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("expenses_trans_category_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransMode", "TransMode")
                        .WithMany("Expenses")
                        .HasForeignKey("TransModeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("expenses_trans_mode_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Transaction", "Transaction")
                        .WithMany("Expenses")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("expenses_transaction_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("expenses_user_id_fkey");

                    b.Navigation("ExpenseType");

                    b.Navigation("TransCategory");

                    b.Navigation("TransMode");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Order", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_client_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PaymentType", "PaymentType")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_payment_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_status_id_fkey");

                    b.Navigation("Client");

                    b.Navigation("PaymentType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderLine", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_lines_order_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("order_lines_product_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Payment", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Payment", null)
                        .WithMany()
                        .HasForeignKey("OriginalPaymentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_original_payment_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Client", "PartyClient")
                        .WithMany("Payments")
                        .HasForeignKey("PartyClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_party_client_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PaymentDirection", "PaymentDirection")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentDirectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_payment_direction_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PaymentType", null)
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId");

                    b.HasOne("HamzaTex.Api.Entities.Payment", null)
                        .WithMany()
                        .HasForeignKey("ReversedByPaymentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_reversed_by_payment_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransMode", "TransMode")
                        .WithMany("Payments")
                        .HasForeignKey("TransModeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_trans_mode_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_transaction_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_user_id_fkey");

                    b.Navigation("PartyClient");

                    b.Navigation("PaymentDirection");

                    b.Navigation("TransMode");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payment_allocations_order_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payment_allocations_payment_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payment_allocations_purchase_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Payment");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ProductUser", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("ProductUsers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_users_product_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", "User")
                        .WithMany("ProductUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_users_user_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Purchase", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.PaymentType", "PaymentType")
                        .WithMany("Purchases")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchases_payment_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.PurchaseStatus", "Status")
                        .WithMany("Purchases")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchases_status_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Client", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchases_supplier_id_fkey");

                    b.Navigation("PaymentType");

                    b.Navigation("Status");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PurchaseLine", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("purchase_lines_product_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_lines_purchase_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.StockMovement", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.MovementSource", "MovementSource")
                        .WithMany("StockMovements")
                        .HasForeignKey("MovementSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("stock_movements_movement_source_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.MovementType", "MovementType")
                        .WithMany("StockMovements")
                        .HasForeignKey("MovementTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("stock_movements_movement_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("stock_movements_product_id_fkey");

                    b.Navigation("MovementSource");

                    b.Navigation("MovementType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Transaction", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_client_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_transactions_orders_OrderId");

                    b.HasOne("HamzaTex.Api.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_product_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.Purchase", "Purchase")
                        .WithMany("Transactions")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_transactions_purchases_PurchaseId");

                    b.HasOne("HamzaTex.Api.Entities.TransCategory", "TransCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("TransCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_trans_category_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransMode", "TransMode")
                        .WithMany("Transactions")
                        .HasForeignKey("TransModeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_trans_mode_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.TransType", "TransType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_trans_type_id_fkey");

                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_user_id_fkey");

                    b.Navigation("Client");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Purchase");

                    b.Navigation("TransCategory");

                    b.Navigation("TransMode");

                    b.Navigation("TransType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HamzaTex.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Expenses");

                    b.Navigation("ProductUsers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Client", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Purchases");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ClientType", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.ExpenseType", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementSource", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.MovementType", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Payment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentDirection", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PaymentType", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("ProductUsers");

                    b.Navigation("PurchaseLines");

                    b.Navigation("StockMovements");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseLines");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.PurchaseStatus", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransCategory", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransMode", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.TransType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.Transaction", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("HamzaTex.Api.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
