/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientPaymentSummary {
  paymentId?: number;
  paymentDate?: string;
  /** @nullable */
  directionName?: string | null;
  /** @nullable */
  modeName?: string | null;
  amount?: number;
  isReversed?: boolean;
}
