/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientPurchaseSummary {
  purchaseId?: number;
  purchaseDate?: string;
  /** @nullable */
  statusName?: string | null;
  total?: number;
  amountPaid?: number;
  outstanding?: number;
  /** @nullable */
  paymentStatus?: string | null;
}
