/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientPaymentSummary {
  paymentId?: number;
  paymentDate?: string;
  /**
     * Hijri equivalent of PaymentDate, formatted for display (e.g. "06 Muharram 1448").
     * @nullable
     */
  paymentDateHijriDisplay?: string | null;
  /** @nullable */
  directionName?: string | null;
  /** @nullable */
  modeName?: string | null;
  amount?: number;
  isReversed?: boolean;
  /**
     * Bill Nos of every Order/Purchase this payment is allocated to. Empty when unallocated.
     * @nullable
     */
  billNos?: string[] | null;
  /** Portion of Amount not yet applied to any Order/Purchase (e.g. released by a cancelled order/purchase). Available as credit. */
  unallocatedAmount?: number;
}
