/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientInvoiceSummary {
  invoiceId?: number;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  issueDate?: string | null;
  /**
     * Hijri equivalent of IssueDate, formatted for display (e.g. "06 Muharram 1448").
     * @nullable
     */
  issueDateHijriDisplay?: string | null;
  /** @nullable */
  dueDate?: string | null;
  /**
     * Hijri equivalent of DueDate, formatted for display (e.g. "06 Muharram 1448").
     * @nullable
     */
  dueDateHijriDisplay?: string | null;
  invoiceStatusId?: number;
  /** @nullable */
  statusName?: string | null;
  totalAmount?: number;
}
