/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  clientTypeId?: number;
  /**
     * Resolved name of the ClientType lookup (e.g. "Customer", "Supplier"). Populated on read.
     * @nullable
     */
  clientTypeName?: string | null;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  creditLimit?: number | null;
  /** @nullable */
  openingBalance?: number | null;
  outstandingBalance?: number;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  /** @nullable */
  createdAt?: string | null;
}
