/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientTransactionSummary {
  transactionId?: number;
  /** @nullable */
  billNo?: string | null;
  /**
     * All distinct bill numbers behind this transaction. A Payment split across several delivered Orders/Purchases carries one entry per bill.
     * @nullable
     */
  billNos?: string[] | null;
  transDate?: string;
  /**
     * Hijri equivalent of TransDate, formatted for display (e.g. "06 Muharram 1448").
     * @nullable
     */
  transDateHijriDisplay?: string | null;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  typeName?: string | null;
  amount?: number;
  isReversal?: boolean;
}
