/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ClientInvoiceSummary {
  invoiceId?: number;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  issueDate?: string | null;
  /** @nullable */
  dueDate?: string | null;
  invoiceStatusId?: number;
  /** @nullable */
  statusName?: string | null;
  totalAmount?: number;
}
