/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { ClientInvoiceSummary } from './clientInvoiceSummary';
import type { ClientOrderSummary } from './clientOrderSummary';
import type { ClientPaymentSummary } from './clientPaymentSummary';
import type { ClientPurchaseSummary } from './clientPurchaseSummary';
import type { ClientTransactionSummary } from './clientTransactionSummary';
import type { MonthlyBalancePoint } from './monthlyBalancePoint';

export interface ClientDetailViewModel {
  clientId?: number;
  /** @nullable */
  clientName?: string | null;
  /** @nullable */
  clientTypeName?: string | null;
  clientTypeId?: number;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  creditLimit?: number | null;
  /** @nullable */
  openingBalance?: number | null;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  totalOrderCount?: number;
  totalOrderAmount?: number;
  totalPurchaseCount?: number;
  totalPurchaseAmount?: number;
  totalPaymentsIn?: number;
  totalPaymentsOut?: number;
  outstanding?: number;
  balance?: number;
  /** @nullable */
  orders?: ClientOrderSummary[] | null;
  /** @nullable */
  purchases?: ClientPurchaseSummary[] | null;
  /** @nullable */
  payments?: ClientPaymentSummary[] | null;
  /** @nullable */
  invoices?: ClientInvoiceSummary[] | null;
  /** @nullable */
  recentTransactions?: ClientTransactionSummary[] | null;
  /** @nullable */
  balanceHistory?: MonthlyBalancePoint[] | null;
}
