/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { DashboardAlertsDto } from './dashboardAlertsDto';
import type { DashboardFinancialsDto } from './dashboardFinancialsDto';
import type { DashboardOperationsDto } from './dashboardOperationsDto';
import type { RecentOrderDto } from './recentOrderDto';

export interface DashboardSummaryDto {
  /** @nullable */
  asOf?: string | null;
  /** @nullable */
  currency?: string | null;
  financials?: DashboardFinancialsDto;
  operations?: DashboardOperationsDto;
  alerts?: DashboardAlertsDto;
  /** @nullable */
  recentOrders?: RecentOrderDto[] | null;
}
