/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ExpenseUpdateViewModel {
  amount?: number;
  transModeId?: number;
  /**
     * Omit or set null to leave the existing date unchanged.
     * @nullable
     */
  expenseDate?: string | null;
  /** @nullable */
  notes?: string | null;
}
