/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ExpenseDto {
  id?: number;
  /** @nullable */
  expenseTypeId?: number | null;
  /** @nullable */
  expenseTypeName?: string | null;
  amount?: number;
  /** @nullable */
  transModeId?: number | null;
  /** @nullable */
  transModeName?: string | null;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  recordedByName?: string | null;
  /** @nullable */
  transCategoryId?: number | null;
  /** @nullable */
  transCategoryName?: string | null;
  /** @nullable */
  transactionId?: number | null;
  expenseDate?: string;
  /** @nullable */
  expenseDateHijri?: string | null;
  /** @nullable */
  expenseDateHijriDisplay?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
}
