/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ExpenseCreateViewModel {
  expenseTypeId?: number;
  amount?: number;
  transModeId?: number;
  /**
     * Optional. Auto-derived from ExpenseTypeId for seeded types (Office→3, Home→4). Required for custom expense types with no built-in mapping.
     * @nullable
     */
  transCategoryId?: number | null;
  /**
     * Omit or set null to use today's UTC date.
     * @nullable
     */
  expenseDate?: string | null;
  /** @nullable */
  notes?: string | null;
}
