/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { InvoiceLineDto } from './invoiceLineDto';
import type { InvoiceTransactionSummary } from './invoiceTransactionSummary';

/**
 * Full invoice detail including lines and linked transactions.
 */
export interface InvoiceDetailDto {
  id?: number;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  purchaseId?: number | null;
  clientId?: number;
  /** @nullable */
  clientName?: string | null;
  /** @nullable */
  clientTypeName?: string | null;
  /** @nullable */
  direction?: string | null;
  /** @nullable */
  type?: string | null;
  invoiceStatusId?: number;
  /** @nullable */
  statusName?: string | null;
  /** @nullable */
  issueDate?: string | null;
  /** @nullable */
  dueDate?: string | null;
  totalAmount?: number;
  amountPaid?: number;
  outstanding?: number;
  /** @nullable */
  notes?: string | null;
  createdAt?: string;
  /** @nullable */
  lines?: InvoiceLineDto[] | null;
  /** @nullable */
  linkedTransactions?: InvoiceTransactionSummary[] | null;
}
