/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { InvoiceDto } from './invoiceDto';

export interface InvoiceDtoResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: InvoiceDto;
  /** @nullable */
  errors?: string[] | null;
}
