/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { InvoiceDto } from './invoiceDto';

/**
 * Client invoice summary: aggregate stats + per-invoice list.
 */
export interface InvoiceByClientDto {
  clientId?: number;
  /** @nullable */
  clientName?: string | null;
  /** @nullable */
  clientTypeName?: string | null;
  /** @nullable */
  direction?: string | null;
  totalInvoiced?: number;
  totalPaid?: number;
  totalReceivable?: number;
  totalPayable?: number;
  /** @nullable */
  invoices?: InvoiceDto[] | null;
}
