/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { InvoiceLineCreateViewModel } from './invoiceLineCreateViewModel';

export interface InvoiceUpdateViewModel {
  /** @nullable */
  invoiceStatusId?: number | null;
  /** @nullable */
  dueDate?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  totalAmount?: number | null;
  /** @nullable */
  lines?: InvoiceLineCreateViewModel[] | null;
}
