/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

/**
 * Aggregate receivable/payable totals and total count across the full (non-paginated) invoice set, excluding cancelled invoices from the amount totals.
 */
export interface InvoiceSummaryDto {
  totalReceivable?: number;
  totalPayable?: number;
  totalCount?: number;
}
