/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { InvoiceLineCreateViewModel } from './invoiceLineCreateViewModel';

export interface InvoiceCreateViewModel {
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  purchaseId?: number | null;
  clientId?: number;
  /** @nullable */
  dueDate?: string | null;
  /**
     * Optional Hijri override for DueDate, "yyyy-MM-dd" in Hijri terms. Omit to auto-compute from DueDate.
     * @nullable
     */
  dueDateHijri?: string | null;
  totalAmount?: number;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  lines?: InvoiceLineCreateViewModel[] | null;
}
