/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

/**
 * Generic shape for all seeded lookup / enum-style tables.
 */
export interface LookupDto {
  id?: number;
  /** @nullable */
  name?: string | null;
}
