/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { LookupDto } from './lookupDto';

/**
 * Combined payload returned by GET /api/Lookups/all.
 * Frontend fetches this once at startup and caches locally.
 */
export interface LookupsAllDto {
  /** @nullable */
  orderStatuses?: LookupDto[] | null;
  /** @nullable */
  purchaseStatuses?: LookupDto[] | null;
  /** @nullable */
  paymentTypes?: LookupDto[] | null;
  /** @nullable */
  paymentDirections?: LookupDto[] | null;
  /** @nullable */
  transTypes?: LookupDto[] | null;
  /** @nullable */
  transModes?: LookupDto[] | null;
  /** @nullable */
  transCategories?: LookupDto[] | null;
  /** @nullable */
  expenseTypes?: LookupDto[] | null;
  /** @nullable */
  movementTypes?: LookupDto[] | null;
  /** @nullable */
  movementSources?: LookupDto[] | null;
  /** @nullable */
  clientTypes?: LookupDto[] | null;
  /** @nullable */
  userRoles?: LookupDto[] | null;
  /** @nullable */
  invoiceStatuses?: LookupDto[] | null;
  /** @nullable */
  units?: LookupDto[] | null;
}
