/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { OrderLineCreateViewModel } from './orderLineCreateViewModel';

export interface OrderCreateViewModel {
  clientId?: number;
  paymentTypeId?: number;
  /**
     * Omit or null to use the current UTC date.
     * @nullable
     */
  orderDate?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  lines?: OrderLineCreateViewModel[] | null;
}
