/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { OrderLineDto } from './orderLineDto';

export interface OrderDto {
  id?: number;
  clientId?: number;
  /** @nullable */
  clientName?: string | null;
  statusId?: number;
  /** @nullable */
  statusName?: string | null;
  paymentTypeId?: number;
  /** @nullable */
  paymentTypeName?: string | null;
  orderDate?: string;
  /** @nullable */
  orderDateHijri?: string | null;
  /** @nullable */
  orderDateHijriDisplay?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  total?: number;
  amountReceived?: number;
  receivable?: number;
  /** @nullable */
  paymentStatus?: string | null;
  /** @nullable */
  orderLines?: OrderLineDto[] | null;
}
