/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface OrderLineDto {
  id?: number;
  orderId?: number;
  productId?: number;
  /** @nullable */
  productName?: string | null;
  qty?: number;
  unitPrice?: number;
  readonly lineTotal?: number;
}
