/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface OrderUpdateViewModel {
  statusId?: number;
  paymentTypeId?: number;
  /** @nullable */
  notes?: string | null;
  /**
     * Omit or null to leave the existing order date unchanged.
     * @nullable
     */
  orderDate?: string | null;
}
