/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { OrderDto } from './orderDto';

export interface OrderDtoListResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: OrderDto[] | null;
  /** @nullable */
  errors?: string[] | null;
}
