/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { PaymentAllocationDto } from './paymentAllocationDto';

export interface PaymentDto {
  id?: number;
  /** @nullable */
  partyClientId?: number | null;
  /** @nullable */
  partyClientName?: string | null;
  /** @nullable */
  paymentDirectionId?: number | null;
  /** @nullable */
  paymentDirectionName?: string | null;
  /** @nullable */
  transModeId?: number | null;
  /** @nullable */
  transModeName?: string | null;
  amount?: number;
  paymentDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  recordedByName?: string | null;
  isReversed?: boolean;
  /** @nullable */
  reversedByPaymentId?: number | null;
  /** @nullable */
  originalPaymentId?: number | null;
  isCashSettled?: boolean;
  /** @nullable */
  allocations?: PaymentAllocationDto[] | null;
}
