/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface PaymentAllocationDto {
  id?: number;
  paymentId?: number;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  purchaseId?: number | null;
  allocatedAmount?: number;
  /**
     * Bill No of the linked Order or Purchase for this allocation.
     * @nullable
     */
  billNo?: string | null;
}
