/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { AllocationItemViewModel } from './allocationItemViewModel';

export interface PaymentCreateViewModel {
  partyClientId?: number;
  paymentDirectionId?: number;
  transModeId?: number;
  amount?: number;
  /**
     * Omit or set null to use the current UTC date.
     * @nullable
     */
  paymentDate?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  allocations?: AllocationItemViewModel[] | null;
}
