/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ProductDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  unit?: string | null;
  /** @nullable */
  defaultCost?: number | null;
  /** @nullable */
  defaultPrice?: number | null;
  /** @nullable */
  quantity?: number | null;
  /** On-hand Quantity minus qty already committed to other non-Delivered, non-Cancelled orders for this product. Use this for stock checks instead of Quantity. */
  availableQuantity?: number;
  /** @nullable */
  averageCost?: number | null;
  /** @nullable */
  averagePrice?: number | null;
  costChangeCount?: number;
  priceChangeCount?: number;
  /** @nullable */
  totalQuantityPurchased?: number | null;
  /** @nullable */
  totalQuantitySold?: number | null;
  /** @nullable */
  reorderLevel?: number | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  createdAt?: string | null;
}
