/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ProductCreateViewModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  sku?: string | null;
  unitId?: number;
  /** @nullable */
  defaultCost?: number | null;
  /** @nullable */
  defaultPrice?: number | null;
  /** @nullable */
  quantity?: number | null;
  /** @nullable */
  reorderLevel?: number | null;
  /** @nullable */
  isActive?: boolean | null;
}
