/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { PurchaseLineCreateViewModel } from './purchaseLineCreateViewModel';

export interface PurchaseCreateViewModel {
  supplierId?: number;
  paymentTypeId?: number;
  /**
     * Omit or null to use the current UTC date.
     * @nullable
     */
  purchaseDate?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  lines?: PurchaseLineCreateViewModel[] | null;
}
