/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { PurchaseLineCreateViewModel } from './purchaseLineCreateViewModel';

export interface PurchaseLinesUpdateViewModel {
  /** @nullable */
  lines?: PurchaseLineCreateViewModel[] | null;
}
