/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { PurchaseLineDto } from './purchaseLineDto';

export interface PurchaseDto {
  id?: number;
  supplierId?: number;
  /** @nullable */
  supplierName?: string | null;
  statusId?: number;
  /** @nullable */
  statusName?: string | null;
  paymentTypeId?: number;
  /** @nullable */
  paymentTypeName?: string | null;
  purchaseDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  total?: number;
  amountPaid?: number;
  payable?: number;
  /** @nullable */
  paymentStatus?: string | null;
  /** @nullable */
  purchaseLines?: PurchaseLineDto[] | null;
}
