/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface RegisterDeviceViewModel {
  /** @nullable */
  pushToken?: string | null;
  /** @nullable */
  deviceType?: string | null;
  /** @nullable */
  appVersion?: string | null;
}
