/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface ResetPasswordViewModel {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  token?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}
