/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface StockMovementsUpdateViewModel {
  productId?: number;
  /** 1 = Purchase (auto In), 2 = Sale (auto Out), 3 = Manual (MovementType required) */
  movementSource?: number;
  /**
     * Required only when MovementSource = 3 (Manual). 1 = In, 2 = Out, 3 = Adjustment.
     * @nullable
     */
  movementType?: number | null;
  qty?: number;
  /** @nullable */
  unitCost?: number | null;
  /** @nullable */
  unitPrice?: number | null;
  /**
     * Omit or null to leave the existing movement date unchanged.
     * @nullable
     */
  movementDate?: string | null;
}
