/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

/**
 * Aggregate in/out quantity totals across the full matching stock movement history (not just one page).
 */
export interface StockMovementsSummaryDto {
  totalIn?: number;
  totalOut?: number;
  /** @nullable */
  totalInUnitLabel?: string | null;
  /** @nullable */
  totalOutUnitLabel?: string | null;
}
