/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface StockMovementsDto {
  id?: number;
  productId?: number;
  /** @nullable */
  productName?: string | null;
  movementSource?: number;
  /** @nullable */
  movementSourceName?: string | null;
  movementType?: number;
  /** @nullable */
  movementTypeName?: string | null;
  qty?: number;
  /** @nullable */
  unitCost?: number | null;
  /** @nullable */
  unitPrice?: number | null;
  /** @nullable */
  averageCostAtMovement?: number | null;
  /** @nullable */
  averagePriceAtMovement?: number | null;
  movementDate?: string;
}
