/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { StockMovementsDto } from './stockMovementsDto';

export interface StockMovementsDtoPagedList {
  /** @nullable */
  items?: StockMovementsDto[] | null;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasNextPage?: boolean;
  readonly hasPreviousPage?: boolean;
}
