/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface StockMovementsCreateViewModel {
  productId?: number;
  /** 1 = Purchase (auto In), 2 = Sale (auto Out), 3 = Manual (MovementType required) */
  movementSource?: number;
  /**
     * Required only when MovementSource = 3 (Manual).
   * 1 = In (adds stock), 2 = Out (removes stock), 3 = Adjustment (no qty change, record only).
   * Ignored for Purchase and Sale — direction is auto-derived.
     * @nullable
     */
  movementType?: number | null;
  qty?: number;
  /** @nullable */
  unitCost?: number | null;
  /** @nullable */
  unitPrice?: number | null;
  /**
     * Omit or null to use the current UTC date.
     * @nullable
     */
  movementDate?: string | null;
  /**
     * Optional Hijri override, "yyyy-MM-dd" in Hijri terms. Omit to auto-compute from MovementDate.
     * @nullable
     */
  movementDateHijri?: string | null;
}
