/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SummaryTotalsViewModel {
  totalSalesAmount?: number;
  totalPurchasesAmount?: number;
  totalExpensesAmount?: number;
  totalOrderCount?: number;
  totalPurchaseCount?: number;
  totalClientsCount?: number;
  /** @nullable */
  salesGrowthPercent?: number | null;
  avgOrderValue?: number;
  activeClientsCount?: number;
  activeClientsChange?: number;
  overdueInvoicesCount?: number;
}
