/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { SyncOrderLineDto } from './syncOrderLineDto';

export interface SyncOrderDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  clientId?: number | null;
  /** @nullable */
  statusId?: number | null;
  /** @nullable */
  paymentTypeId?: number | null;
  orderDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  orderLines?: SyncOrderLineDto[] | null;
  /** @nullable */
  operation?: string | null;
}
