/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { SyncPurchaseLineDto } from './syncPurchaseLineDto';

export interface SyncPurchaseDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  supplierId?: number | null;
  /** @nullable */
  statusId?: number | null;
  /** @nullable */
  paymentTypeId?: number | null;
  purchaseDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  purchaseLines?: SyncPurchaseLineDto[] | null;
  /** @nullable */
  operation?: string | null;
}
