/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { SyncInvoiceLineDto } from './syncInvoiceLineDto';

export interface SyncInvoiceDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  id?: number;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  purchaseId?: number | null;
  /** @nullable */
  clientId?: number | null;
  /** @nullable */
  createdByUserId?: number | null;
  invoiceStatusId?: number;
  /** @nullable */
  issueDate?: string | null;
  /** @nullable */
  dueDate?: string | null;
  totalAmount?: number;
  /** @nullable */
  notes?: string | null;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  invoiceLines?: SyncInvoiceLineDto[] | null;
}
