/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncPaymentAllocationDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  id?: number;
  paymentId?: number;
  /** @nullable */
  paymentLocalId?: string | null;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  purchaseId?: number | null;
  /** @nullable */
  invoiceId?: number | null;
  allocatedAmount?: number;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
}
