/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncProductDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  unit?: string | null;
  /** @nullable */
  defaultCost?: number | null;
  /** @nullable */
  defaultPrice?: number | null;
  /** @nullable */
  quantity?: number | null;
  /** @nullable */
  averageCost?: number | null;
  /** @nullable */
  averagePrice?: number | null;
  /** @nullable */
  costChangeCount?: number | null;
  /** @nullable */
  priceChangeCount?: number | null;
  /** @nullable */
  totalQuantityPurchased?: number | null;
  /** @nullable */
  totalQuantitySold?: number | null;
  /** @nullable */
  reorderLevel?: number | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  operation?: string | null;
}
