/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncItemResultDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  serverVersion?: number | null;
  /** @nullable */
  serverData?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
