/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncStockMovementDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  movementTypeId?: number | null;
  /** @nullable */
  movementSourceId?: number | null;
  /** @nullable */
  qty?: number | null;
  /** @nullable */
  unitCost?: number | null;
  /** @nullable */
  unitPrice?: number | null;
  movementDate?: string;
  /** @nullable */
  updatedAt?: string | null;
}
