/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncMonthlyProfitLossDto {
  id?: number;
  /** @nullable */
  month?: string | null;
  /** @nullable */
  totalSales?: number | null;
  /** @nullable */
  totalPurchases?: number | null;
  /** @nullable */
  totalExpenses?: number | null;
  /** @nullable */
  grossProfit?: number | null;
  /** @nullable */
  netProfit?: number | null;
}
