/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncPaymentDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  /** @nullable */
  partyClientId?: number | null;
  /** @nullable */
  paymentDirectionId?: number | null;
  /** @nullable */
  transModeId?: number | null;
  amount?: number;
  paymentDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
}
