/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface SyncClientDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  serverId?: number | null;
  version?: number;
  forceOverwrite?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  clientTypeId?: number | null;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  creditLimit?: number | null;
  /** @nullable */
  openingBalance?: number | null;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
}
