/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { SyncItemResultDto } from './syncItemResultDto';

export interface SyncPushResultDto {
  /** @nullable */
  results?: SyncItemResultDto[] | null;
  acceptedCount?: number;
  rejectedCount?: number;
  serverTime?: string;
}
