/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { SyncClientBalanceDto } from './syncClientBalanceDto';
import type { SyncClientDto } from './syncClientDto';
import type { SyncExpenseDto } from './syncExpenseDto';
import type { SyncInvoiceDto } from './syncInvoiceDto';
import type { SyncLookupDto } from './syncLookupDto';
import type { SyncMonthlyCreditDebitDto } from './syncMonthlyCreditDebitDto';
import type { SyncMonthlyProfitLossDto } from './syncMonthlyProfitLossDto';
import type { SyncOrderDto } from './syncOrderDto';
import type { SyncPaymentDto } from './syncPaymentDto';
import type { SyncProductDto } from './syncProductDto';
import type { SyncPurchaseDto } from './syncPurchaseDto';
import type { SyncStockMovementDto } from './syncStockMovementDto';
import type { SyncTransactionDto } from './syncTransactionDto';

export interface SyncFullPullResponseDto {
  /** @nullable */
  clients?: SyncClientDto[] | null;
  /** @nullable */
  products?: SyncProductDto[] | null;
  /** @nullable */
  orders?: SyncOrderDto[] | null;
  /** @nullable */
  purchases?: SyncPurchaseDto[] | null;
  /** @nullable */
  payments?: SyncPaymentDto[] | null;
  /** @nullable */
  expenses?: SyncExpenseDto[] | null;
  /** @nullable */
  stockMovements?: SyncStockMovementDto[] | null;
  /** @nullable */
  transactions?: SyncTransactionDto[] | null;
  /** @nullable */
  invoices?: SyncInvoiceDto[] | null;
  /** @nullable */
  userRoles?: SyncLookupDto[] | null;
  /** @nullable */
  clientTypes?: SyncLookupDto[] | null;
  /** @nullable */
  orderStatuses?: SyncLookupDto[] | null;
  /** @nullable */
  purchaseStatuses?: SyncLookupDto[] | null;
  /** @nullable */
  paymentTypes?: SyncLookupDto[] | null;
  /** @nullable */
  paymentDirections?: SyncLookupDto[] | null;
  /** @nullable */
  transTypes?: SyncLookupDto[] | null;
  /** @nullable */
  transModes?: SyncLookupDto[] | null;
  /** @nullable */
  transCategories?: SyncLookupDto[] | null;
  /** @nullable */
  expenseTypes?: SyncLookupDto[] | null;
  /** @nullable */
  movementTypes?: SyncLookupDto[] | null;
  /** @nullable */
  movementSources?: SyncLookupDto[] | null;
  /** @nullable */
  invoiceStatuses?: SyncLookupDto[] | null;
  /** @nullable */
  clientBalances?: SyncClientBalanceDto[] | null;
  /** @nullable */
  monthlyProfitLoss?: SyncMonthlyProfitLossDto[] | null;
  /** @nullable */
  monthlyCreditDebit?: SyncMonthlyCreditDebitDto[] | null;
  serverTime?: string;
}
