/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */
import type { TestPushRequestTemplateVars } from './testPushRequestTemplateVars';

export interface TestPushRequest {
  /**
     * Notification type key from the catalog (e.g. "order_delivered").
     * @nullable
     */
  notificationType?: string | null;
  /**
     * Template variable substitutions (e.g. orderId, clientName, amount).
     * @nullable
     */
  templateVars?: TestPushRequestTemplateVars;
}
