/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

/**
 * Template variable substitutions (e.g. orderId, clientName, amount).
 * @nullable
 */
export type TestPushRequestTemplateVars = {[key: string]: string} | null;
