/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface TransactionDto {
  id?: number;
  /** @nullable */
  clientId?: number | null;
  /** @nullable */
  clientName?: string | null;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  purchaseId?: number | null;
  /** @nullable */
  transTypeId?: number | null;
  /** @nullable */
  transTypeName?: string | null;
  /** @nullable */
  transModeId?: number | null;
  /** @nullable */
  transModeName?: string | null;
  /** @nullable */
  transCategoryId?: number | null;
  /** @nullable */
  transCategoryName?: string | null;
  amount?: number;
  transDate?: string;
  /** @nullable */
  transDateHijri?: string | null;
  /** @nullable */
  transDateHijriDisplay?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /**
     * Derived: "Order #N" | "Purchase #N" | "Expense" | "Payment" | "Manual"
     * @nullable
     */
  source?: string | null;
  /** True only for manually-created entries — controls edit/delete eligibility on the frontend. */
  isManual?: boolean;
}
