/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface TransactionUpdateViewModel {
  amount?: number;
  transCategoryId?: number;
  /** Required. Replaces the existing transaction date. */
  transDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  clientId?: number | null;
  /**
     * Defaults to 1 (Debit) if omitted.
     * @nullable
     */
  transTypeId?: number | null;
  /**
     * Defaults to 1 (Cash) if omitted.
     * @nullable
     */
  transModeId?: number | null;
}
