/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * HamzaTex API
 * Textile ERP — staff mobile + admin backend. All endpoints require a JWT Bearer token except Auth.
 * OpenAPI spec version: v1
 */

export interface UserDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  userName?: string | null;
  roleId?: number;
  /** @nullable */
  phoneNumber?: string | null;
  isActive?: boolean;
  createdAt?: string;
}
