import { StyleSheet } from 'react-native';

import { colors } from '@theme/colors';
import { typography } from '@theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
  },
  heroWrapper: {
    margin: 20,
    borderRadius: 28,
    overflow: 'hidden',
  },
  heroGradient: {
    paddingHorizontal: 24,
    paddingTop: 36,
    paddingBottom: 28,
  },
  orbTopRight: {
    position: 'absolute',
    top: -60,
    right: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: colors.overlayWhite08,
  },
  orbBottomLeft: {
    position: 'absolute',
    bottom: -70,
    left: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  wordmarkContainer: {
    alignItems: 'center',
    gap: 8,
  },
  logoBox: {
    width: 90,
    height: 90,
    borderRadius: 26,
    backgroundColor: colors.overlayWhite18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.shadowBlack,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.2,
    shadowRadius: 40,
    elevation: 12,
  },
  brandName: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 42,
    color: colors.textInverse,
    letterSpacing: -0.8,
    lineHeight: 62,
    textAlign: 'center',
    fontWeight: '600',
  },
  brandSubtitle: {
    fontFamily: typography.fontFamily.semibold,
    fontSize: 18,
    color: colors.overlayWhite72,
    letterSpacing: 2.4,
    marginTop: 2,
    textAlign: 'center',
    fontWeight: 'semibold',
  },
  heroTagline: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 16,
    color: colors.overlayWhite86,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: 28,
    fontWeight: "600",
  },
  statsWrapper: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  statsCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 10,
    flexDirection: 'row',
    shadowColor: colors.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statItemBorder: {
    borderLeftWidth: 1,
    borderLeftColor: colors.divider,
  },
  statValue: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 18,
    color: colors.primary,
    letterSpacing: -0.4,
  },
  statLabel: {
    fontFamily: typography.fontFamily.semibold,
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  featuresWrapper: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 10,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    shadowColor: colors.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  iconTile: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureLabel: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 14,
    color: colors.text,
  },
  featureSub: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  ctaWrapper: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 16,
    color: colors.textInverse,
  },
  signInRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  signInText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.textSecondary,
  },
  signInLink: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 13,
    color: colors.primary,
  },
  termsText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 11,
    color: colors.textTertiary,
    textAlign: 'center',
    marginTop: 14,
    lineHeight: 16,
  },
  termsLink: {
    fontFamily: typography.fontFamily.bold,
    color: colors.primary,
  },
});
